project_id = "jrzcaftckeyingxygljz"

[functions.send-share-notification]
verify_jwt = false

[functions.sync-to-monday]
verify_jwt = false

[functions.get-monday-boards]
verify_jwt = false

[functions.get-admin-users]
verify_jwt = false
